# Generated by Django 3.1.4 on 2022-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coustom_user', models.CharField(max_length=20)),
                ('categories', models.ManyToManyField(to='testapp.OrderItem')),
                ('chef', models.ManyToManyField(to='testapp.Chef')),
            ],
        ),
    ]
