# Generated by Django 3.1.4 on 2022-01-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='username',
        ),
    ]
