# Generated by Django 3.1.4 on 2022-01-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20220118_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
