# Generated by Django 3.1.4 on 2022-01-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
