# Generated by Django 3.1.4 on 2022-01-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20220118_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
