# Generated by Django 3.1.4 on 2022-01-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
